apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: edge-app-settings
  namespace: cluster-config
spec:
  chart:
    spec:
      chart: edge-app-settings
      sourceRef:
        kind: HelmRepository
        name: edge-app-settings
        namespace: cluster-config
  values:
    configMap:
      name: edge-app-configmap
      data:
        TEMPERATURE: \"20\"
        PRESSURE: \"74\"
        VELOCITY: \"13\"
    secret:
      name: edge-app-secret
      stringData:
        USERNAME: arcuser-0
        PASSWORD: cfdaf45b930677948456
        TOKEN: Y2ZkYWY0NWI5MzA2Nzc5NDg0NTYK
