apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: edge-app-settings
  namespace: cluster-config
spec:
  interval: 5m
  url: https://marvin-garcia.github.io/gitops-playground/