apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: edge-app-settings
spec:
  values:
    configMap:
      name: edge-app-configmap
      data:
        TEMPERATURE: 13
        PRESSURE: 90
        VELOCITY: 44
    secret:
      name: edge-app-secret
      stringData:
        USERNAME: arcuser-4
        PASSWORD: 4bfa00af15b2d9ebee50
        TOKEN: NGJmYTAwYWYxNWIyZDllYmVlNTAK
