apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: cluster-config
spec:
  values:
    controller:
      service:
        type: LoadBalancer
        externalIPs:
        - '172.16.1.5'
