{{- if .Values.configMap -}}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- with .Values.configMap.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ .Values.configMap.name }}
  namespace: {{ .Release.Namespace }}
data:
  {{ toYaml .Values.configMap.data | nindent 2 }}
{{- end }}
