{{- if .Values.secret -}}
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- with .Values.secret.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ .Values.secret.name }}
  namespace: {{ .Release.Namespace }}
stringData:
  {{ toYaml .Values.secret.stringData | nindent 2 }}
{{- end }}
