apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: edge-app
  namespace: cluster-config
spec:
  targetNamespace: edge-app
  releaseName: edge-app
  chart:
    spec:
      chart: edge-app
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: edge-app
        namespace: cluster-config
      version: ">=1.0.2"
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    image:
      repository: marvingarcia/edge-app
      tag: "4"
    envFrom:
    - configMapRef:
        name: edge-app-configmap
    - secretRef:
        name: edge-app-secret
    # annotations:
    #   reloader.stakater.com/auto: "true"
    volumes:
    - name: configmap-volume
      configMap:
        name: edge-app-configmap
    - name: secret-volume
      secret:
        name: edge-app-secret
    volumeMounts:
    - name: configmap-volume
      mountPath: /app/configmap-volume
      readOnly: true
    - name: secret-volume
      mountPath: /app/secret-volume
      readOnly: true
    ingress:
      enabled: true
      className: nginx
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /
        nginx.ingress.kubernetes.io/use-regex: "false"
      hosts:
        - paths:
            - path: /
              pathType: Prefix
