apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: edge-app
  namespace: cluster-config
spec:
  targetNamespace: edge-app
  releaseName: edge-app
  chart:
    spec:
      chart: edge-app
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: edge-app
        namespace: cluster-config
      version: ">=0.1.0"
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    image:
      repository: magaracr.azurecr.io/edge-app
      tag: "1"
    envFrom:
    - configMapRef:
        name: edge-app-configmap
    - secretRef:
        name: edge-app-secrets
    ingress:
      enabled: true
      className: nginx
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /
        nginx.ingress.kubernetes.io/use-regex: "false"
      hosts:
        - paths:
            - path: /
              pathType: Prefix
