apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: stakater-reloader
  namespace: cluster-config
spec:
  targetNamespace: stakater
  releaseName: stakater-reloader
  chart:
    spec:
      chart: stakater-reloader
      sourceRef:
        kind: HelmRepository
        name: stakater-reloader
        namespace: cluster-config
  interval: 1h
