apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: reloader
  namespace: cluster-config
spec:
  targetNamespace: stakater
  releaseName: reloader
  chart:
    spec:
      chart: reloader
      sourceRef:
        kind: HelmRepository
        name: reloader
        namespace: cluster-config
  interval: 1h
