name: NGINX Ingress Helm Package
on:
  push:
    paths:
    - 'infrastructure/ingress-nginx/chart/**'
    branches:
    - main
  workflow_dispatch:
    inputs:
      comment:
        description: 'Run comments'
        required: false
jobs:
  call-helm-package:
    uses: marvin-garcia/gitops-playground/.github/workflows/helm-package.yaml@main
    with:
      repo_url: 'https://marvin-garcia.github.io/gitops-playground/'
      package_path: 'infrastructure/ingress-nginx/'
      chart_path: 'infrastructure/ingress-nginx/chart/'
      gh_username: marvingarcia
      gh_email: noreply@github.com
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
